# Generated by Django 6.0 on 2026-01-04 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0004_datospersonales_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventagarage',
            name='descripcion',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
