# Generated by Django 6.0 on 2026-01-04 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0011_datospersonales_fotodeperfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datospersonales',
            name='descripcionperfil',
            field=models.CharField(max_length=500),
        ),
    ]
