# Generated by Django 6.0 on 2026-01-07 23:28

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0012_alter_datospersonales_descripcionperfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventagarage',
            name='rutaproducto',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='ruta del producto'),
        ),
    ]
