# Generated by Django 6.0 on 2026-01-14 15:20

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0017_datospersonales_titulodescripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursorealizado',
            name='certificadoimagen',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='certificado'),
        ),
    ]
