# Generated by Django 6.0 on 2026-01-14 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0018_cursorealizado_certificadoimagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cursorealizado',
            old_name='certificadoimagen',
            new_name='imagendelacolumnadearriba',
        ),
    ]
