# Generated by Django 6.0 on 2026-01-14 15:29

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0019_rename_certificadoimagen_cursorealizado_imagendelacolumnadearriba'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursorealizado',
            name='imagendelacolumnadearriba',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='certificado_IMG'),
        ),
        migrations.AlterField(
            model_name='cursorealizado',
            name='rutacertificado',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='certificado_PDF'),
        ),
    ]
