# Generated by Django 6.0 on 2026-01-20 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0020_alter_cursorealizado_imagendelacolumnadearriba_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursorealizado',
            name='descripcioncurso',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='cargodesempenado',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='descripcionfunciones',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='productosacademicos',
            name='descripcion',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='reconocimientos',
            name='descripcionreconocimiento',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
