# Generated by Django 6.0 on 2026-01-25 20:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0022_ventagarage_fechapublicacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventagarage',
            name='fechapublicacion',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
