# Generated by Django 6.0 on 2026-01-25 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0023_alter_ventagarage_fechapublicacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSecciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mostrar_datos_personales', models.BooleanField(default=True)),
                ('mostrar_experiencia_laboral', models.BooleanField(default=True)),
                ('mostrar_reconocimientos', models.BooleanField(default=True)),
                ('mostrar_cursos', models.BooleanField(default=True)),
                ('mostrar_productos_academicos', models.BooleanField(default=True)),
                ('mostrar_productos_laborales', models.BooleanField(default=True)),
                ('mostrar_venta_garage', models.BooleanField(default=True)),
                ('mostrar_pdf', models.BooleanField(default=True)),
                ('perfil', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracion', to='perfil.datospersonales')),
            ],
        ),
    ]
