# Generated by Django 6.0 on 2026-01-25 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0024_configuracionsecciones'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConfiguracionSecciones',
        ),
    ]
