# Generated by Django 6.0 on 2026-01-25 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0025_delete_configuracionsecciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productosacademicos',
            name='clasificador',
            field=models.CharField(blank=True, choices=[('ARTICULO', 'Artículo científico'), ('PONENCIA', 'Ponencia'), ('PROYECTO', 'Proyecto de investigación'), ('LIBRO', 'Libro'), ('CAPITULO', 'Capítulo de libro'), ('RECURSO', 'Recurso didáctico')], max_length=20, null=True),
        ),
    ]
