# Generated by Django 6.0 on 2026-01-25 22:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0026_alter_productosacademicos_clasificador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datospersonales',
            name='apellidos',
            field=models.CharField(max_length=60, validators=[django.core.validators.RegexValidator(message='Este campo solo debe contener letras.', regex='^[a-zA-ZÁÉÍÓÚáéíóúÑñ\\s]+$')]),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='estadocivil',
            field=models.CharField(choices=[('Soltero', 'Soltero'), ('Casado', 'Casado'), ('Divorciado', 'Divorciado'), ('Viudo', 'Viudo')], max_length=15),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='licenciaconducir',
            field=models.CharField(choices=[('Sí', 'Sí'), ('No', 'No')], default='No', max_length=2),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='lugarnacimiento',
            field=models.CharField(help_text='Ej: Manta - Manabí', max_length=60),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='nacionalidad',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Este campo solo debe contener letras.', regex='^[a-zA-ZÁÉÍÓÚáéíóúÑñ\\s]+$')]),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='nombres',
            field=models.CharField(max_length=60, validators=[django.core.validators.RegexValidator(message='Este campo solo debe contener letras.', regex='^[a-zA-ZÁÉÍÓÚáéíóúÑñ\\s]+$')]),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='numerocedula',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Este campo solo debe contener números.', regex='^[0-9]+$')]),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='sitioweb',
            field=models.URLField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='telefonoconvencional',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Este campo solo debe contener números.', regex='^[0-9]+$')]),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='telefonofijo',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Este campo solo debe contener números.', regex='^[0-9]+$')]),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='sitiowebempresa',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
