# Generated by Django 6.0 on 2026-01-27 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0028_reconocimientos_reconocimientodelacolumnadearriba_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursorealizado',
            name='fechainicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='fechanacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='fechainiciogestion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reconocimientos',
            name='fechareconocimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
