# Generated by Django 6.0 on 2026-01-27 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0029_alter_cursorealizado_fechainicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursorealizado',
            name='fechainicio',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='fechainiciogestion',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='productolaboral',
            name='fechaproducto',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reconocimientos',
            name='fechareconocimiento',
            field=models.DateField(),
        ),
    ]
