# Generated by Django 6.0 on 2026-01-27 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0030_alter_cursorealizado_fechainicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursorealizado',
            name='fechainicio',
            field=models.DateField(null=True),
        ),
    ]
